import DaisyCarousel from '@/common/components/organism/DaisyCarousel';
import EventCalendar from '@/common/components/organism/EventCalendar';
import Footer from '@/common/components/organism/Footer';
import PengumumanContent from '@/common/components/organism/PengumumanContent';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import GroupsRoundedIcon from '@mui/icons-material/GroupsRounded';
import PermMediaRoundedIcon from '@mui/icons-material/PermMediaRounded';
import { Box, Button, Grid, Paper, Stack, Typography } from '@mui/material';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Appnav from '../common/components/organism/Appnav';
// import UpdatesNotification from '@/common/components/organism/UpdatesNotification';
import ContainerPage from '@/common/components/atoms/ContainerPage';
import { getPengumumanList } from '@/services/pengumuman';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import { useRouter } from 'next/router';
import { useCallback, useEffect, useState } from 'react';

export default function Home() {
  const { isReady } = useRouter();
  const [pengumumanData, setPengumumanData] = useState<Array<any>>([]);

  const getPengumumanData = useCallback(async () => {
    const data = await getPengumumanList();
    setPengumumanData(data);
  }, [getPengumumanList]);

  useEffect(() => {
    if (isReady) {
      getPengumumanData();
    }
  }, [isReady]);
  return (
    <>
      <Head>
        <title>Halaman Beranda - Sistem Informasi Manajemen Pelayanan dan Berita</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className='bg-white'>
        {/* <UpdatesNotification /> */}
        <Box className='w-screen xs:h-[70vh] lg:h-[80vh] relative flex items-center'>
          <Appnav />
          <Image src='/images/hero-5.jpg' alt="Hero's Site" layout='fill' objectFit='cover' className='pt-0 brightness-[0.3]' />
          <ContainerPage>
            <Box className='absolute text-grey xs:w-[320px] md:w-[600px] xs:-translate-y-24 md:-translate-y-32 -translate-x-12'>
              <Typography variant='h4' className='font-bold xs:text-[1.75rem] md:text-[2.75rem] xs:leading-tight md:leading-none mb-2'>Sistem Informasi Manajemen Pelayanan dan Berita</Typography>
              <Typography variant='h5' className='mb-4'>UPT Hubungan Masyarakat dan Media UNS</Typography>
              <Link href='/sign-in'>
                <Button variant='contained' color='primary' size='large' className='px-4 py-2 capitalize xs:w-[200px] md:w-[250px] text-[1rem]' endIcon={<ArrowForwardIcon />}>Ajukan Layanan</Button>
              </Link>
            </Box>
          </ContainerPage>
        </Box>
        <ContainerPage>
          <Paper variant='outlined' sx={{ borderColor: '#e5e7eb' }} className='-translate-y-14 xs:-translate-y-9 shadow-lg rounded-xl p-5 px-4'>
            <Grid container spacing={2} className='px-5'>
              <Grid item xs={4}>
                <Link href="/users/layanan-humas" className='grid place-items-center align-middle hover:brightness-125'>
                  <GroupsRoundedIcon color='primary' sx={{ fontSize: { xs: 50, md: 40 } }} />
                  <Typography variant='h6' className='font-bold text-center' sx={{ display: { xs: 'none', md: 'block' } }}>Layanan Hubungan Masyarakat</Typography>
                </Link>
              </Grid>
              <Grid item xs={4}>
                <Link href='/users/layanan-publikasi' className='grid place-items-center align-middle hover:brightness-125'>
                  <CloudUploadIcon color='primary' sx={{ fontSize: { xs: 50, md: 40 } }} />
                  <Typography variant='h6' className='font-bold text-center' sx={{ display: { xs: 'none', md: 'block' } }}>Layanan Publikasi</Typography>
                </Link>
              </Grid>
              <Grid item xs={4}>
                <Link href='/users/layanan-media' className='grid place-items-center align-middle hover:brightness-125'>
                  <PermMediaRoundedIcon color='primary' sx={{ fontSize: { xs: 50, md: 40 } }} />
                  <Typography variant='h6' className='font-bold text-center' sx={{ display: { xs: 'none', md: 'block' } }}>Layanan Media</Typography>
                </Link>
              </Grid>
            </Grid>
          </Paper>
          <Grid container spacing={2}>
            <Grid item xs={12} md={5}>
              <Stack spacing={2}>
                <Typography variant='h5' className='font-bold mb-2' color='primary'>Kalendar Agenda</Typography>
                <Box className='justify-center flex'>
                  <EventCalendar />
                </Box>
              </Stack>
            </Grid>
            <Grid item xs={12} md={7}>
              <Box>
                <Typography variant='h5' className='font-bold mb-2' color='primary'>Agenda Terkini</Typography>
                <Box className='justify-center flex max-w-[40rem]'>
                  <DaisyCarousel />
                </Box>
                <Box className='flex justify-center mt-6 mb-10'>
                  <Link href='/events'>
                    <Button variant='outlined' color='primary' size='small' className='rounded-lg capitalize'>Lihat Lainnya</Button>
                  </Link>
                </Box>
              </Box>
            </Grid>
          </Grid>
          <Box className='mt-4'>
            <Typography variant='h5' className='font-bold mb-6' color='primary'>Pengumuman Sistem</Typography>
            <Grid container spacing={2} className='my-4 -mx-1'>
              <PengumumanContent data={pengumumanData} />
            </Grid>
            <Box className='flex justify-center mb-8'>
              <Link href='/pengumuman'>
                <Button variant='outlined' color='primary' size='medium' className='capitalize rounded-lg'>Lihat Lainnya</Button>
              </Link>
            </Box>
          </Box>
        </ContainerPage>
        <Footer />
      </Box>
    </>
  );
}
